name: site

size: S

build:
  flavor: none

type: ruby:3.2

variables:
  env:
    JEKYLL_ENV: production

web:
  locations:
    '/':
      root: '_site'
      index:
        - index.html
      passthru: '/404/index.html'
      expires: 5m
      scripts: false
      rules:
        '\.(js|css|jpe?g|png|gif|ico|svg)$':
          expires: 10m

hooks:
  build: |
    set -e
    gem install bundler
    bundle install
    jekyll build
