name: site

build:
  flavor: none

type: ruby:2.5

disk: 1024

web:
  locations:
    '/':
      root: '_site'
      index:
        - index.html
      passthru: false

hooks:
  build: |
    set -e
    gem install bundler
    bundle install
    jekyll build
    command -v platform || curl -sfS https://platform.sh/cli/installer | php

crons:
  # Automatically redeploy master every month.
  redeploy:
    spec: '0 0 1 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        platform vset _redeploy "$(date)" --yes --no-wait
      fi
