name: site

size: S

build:
  flavor: none

type: ruby:2.5

variables:
  env:
    JEKYLL_ENV: production

web:
  locations:
    '/':
      root: '_site'
      index:
        - index.html
      passthru: '/404/index.html'
      expires: 5m
      scripts: false
      rules:
        '\.(js|css|jpe?g|png|gif|ico|svg)$':
          expires: 10m

hooks:
  build: |
    set -e
    gem install bundler
    bundle install
    jekyll build
    command -v platform >/dev/null || curl -sfS https://platform.sh/cli/installer | php

crons:
  # Automatically redeploy master every month.
  redeploy:
    spec: '0 0 1 * *'
    cmd: |
      if [ "$PLATFORM_BRANCH" = master ]; then
        platform redeploy --yes --no-wait
      fi
