https://{default}:
  type: upstream
  upstream: site:http
  cache:
    enabled: true
    cookies: []

https://www.{default}:
  type: redirect
  to: https://{default}

https://{default}/apps:
  type: upstream
  upstream: cut-outs-backend:http
  cache:
    enabled: true
    cookies: []
