name: apps-backend

type: "python:3.6"

disk: 3072

variables:
  env:
    APP_PATH: '/apps'

web:
  commands:
    start: python server.py

  locations:
    '/apps/static':
      root: 'app/static'
      allow: true
      passthru: '/404/index.html'
      expires: 1h

dependencies:
    python3:
       pipenv: '*'

mounts:
  'download':
    source: local
    source_path: 'download'

  'resources/scores':
    source: local
    source_path: 'resources/scores'

  'app/templates/writable':
    source: local
    source_path: 'app/templates/writable'

relationships:
  site: "site:http"

hooks:
  build: |
    set -e
    pipenv install --system

    npm install
    cp node_modules/opensheetmusicdisplay/build/opensheetmusicdisplay.min.js ./app/static/

    if [ ! -d When-in-Rome ]; then
      git clone https://github.com/MarkGotham/When-in-Rome.git When-in-Rome
    fi
  deploy: |
    set -e
    touch resources/scores/lieder.jsonl
    curl --max-time 5 -sS site.internal/template/index.html > app/templates/writable/base.html
  post_deploy: |
    cd app
    timeout 600 python -c 'from indexer import *; get_lieder_index("../When-in-Rome/Corpus/OpenScore-LiederCorpus", index_filename="../resources/scores/lieder.jsonl", rebuild=True)'
